# Generated by Django 6.0.2 on 2026-06-29 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='telegram_chat_id',
            field=models.BigIntegerField(blank=True, help_text='Telegram group chat ID', null=True),
        ),
    ]
