# Generated by Django 6.0.2 on 2026-07-17 09:56

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('auid', models.CharField(max_length=13)),
                ('feedback', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='StudentProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('auid', models.CharField(max_length=32, unique=True)),
                ('user_id', models.IntegerField(blank=True, null=True)),
                ('student_id', models.IntegerField(blank=True, null=True)),
                ('full_name', models.CharField(blank=True, max_length=255)),
                ('acharya_email', models.EmailField(blank=True, max_length=254, null=True)),
                ('mobile', models.CharField(blank=True, max_length=32)),
                ('program_name', models.CharField(blank=True, max_length=255)),
                ('specialization', models.CharField(blank=True, max_length=255)),
                ('ac_year', models.CharField(blank=True, max_length=50)),
                ('current_city', models.CharField(blank=True, max_length=100)),
                ('last_synced_at', models.DateTimeField(auto_now=True)),
                ('present_count', models.PositiveIntegerField(default=0)),
                ('absent_count', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='AllowedStudents',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('auid', models.CharField(max_length=13)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('notes', models.TextField(blank=True)),
                ('is_active', models.BooleanField(default=True)),
                ('deny_message', models.TextField(blank=True, default='You are not allowed to access this page please contact Akhrojon')),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
