# Generated by Django 6.0.2 on 2026-02-18 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='allowedstudents',
            name='absent_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='allowedstudents',
            name='present_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
