# Generated by Django 6.0.2 on 2026-02-18 00:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_allowedstudents_absent_count_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='allowedstudents',
            name='absent_count',
        ),
        migrations.RemoveField(
            model_name='allowedstudents',
            name='present_count',
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='absent_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='studentprofile',
            name='present_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
