# Generated by Django 6.0.2 on 2026-06-20 22:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_feedback'),
    ]

    operations = [
        migrations.RenameField(
            model_name='allowedstudents',
            old_name='creted_at',
            new_name='created_at',
        ),
    ]
