# Generated by Django 6.0.2 on 2026-06-27 14:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('group', '0001_initial'),
        ('lessons', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='group',
            field=models.ForeignKey(default=500, on_delete=django.db.models.deletion.CASCADE, related_name='lessons', to='group.group'),
            preserve_default=False,
        ),
    ]
